controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#je crée une route pour la page d'accueil
#home:
#   path: /
#   controller: App\Controller\HomeController::index