nelmio_cors:
  defaults:
    origin_regex: true
    allow_credentials: true
    allow_origin: ['http://localhost:5173', 'http://127.0.0.1:5173']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    expose_headers: ['Link']
    max_age: 3600

  paths:
    '^/api/':
      allow_origin: ['http://localhost:5173', 'http://127.0.0.1:5173']
      allow_credentials: true
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
      expose_headers: ['Authorization']
      max_age: 3600




